language: node_js
node_js:
  # LTS versions as of feb 2017
  - "6.10"
  # current versions as of feb 2017
  - "7.6"
notifications:
  email: false
before_script:
  - yarn install --ignore-engines
script:
  - npm test
  - npm run build
after_script:
  - npm run test-coverage
